name: Bug Report
description: Report a bug/issue
labels: [bug]
title: "Bug Report: "
body:
  - type: markdown
    attributes:
      value: |
        **Before submitting an issue, please make sure to search the [Issues](https://github.com/crnvl96/lazydocker.nvim/issues) and [Discussions](https://github.com/crnvl96/lazydocker.nvim/discussions)**
  - type: markdown
    attributes:
      value: |
        **Have in mind that this plugin is just a wrapper for [lazydocker](https://github.com/jesseduffield/lazydocker) itself, so any issues regarding lazydocker itself should be addressed in its own repository**
  - type: checkboxes
    attributes:
      label: Checklist
      description: Please make sure to search the issues first and check only the relevant boxes below.
      options:
        - label: I have searched exisiting issues / discussions
          required: true
        - label: I have read `lazydocker` documentation if relevant
          required: false
  - type: input
    attributes:
      label: "Operating system"
      placeholder: "e.g. Linux, Windows, Mac, etc"
    validations:
      required: true
  - type: input
    attributes:
      label: "Shell"
      placeholder: "e.g. bash, zsh, fish, etc"
    validations:
      required: true
  - type: input
    attributes:
      label: "Neovim version (`nvim --version`)"
      placeholder: "NVIM v0.10.0-dev-2739+ge2224a793"
    validations:
      required: true
  - type: input
    attributes:
      label: "Lazydocker version (`lazydocker --version`)"
      placeholder: "e.g. 0.23.3 (152b365)"
    validations:
      required: true
  - type: textarea
    id: config
    attributes:
      label: lazydocker.nvim configuration
      description: |
        lazydocker.nvim setup options
      render: lua
      value: |
        ```lua
        require('lazydocker').setup({})
        ```
  - type: textarea
    attributes:
      label: Describe the bug / steps to reproduce
      description: |
        Please describe your issue with as much details as you can, what you've tested and your findings, would be nice if you can provide reproduction steps / code.
    validations:
      required: true
