name: Linting and style checking
on:
  push:
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.actor }}
  cancel-in-progress: true
jobs:
  stylua:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.STYLUA_ACTION_TOKEN }}
          version: v0.19.0
          args: --color always --respect-ignores --check . # CLI arguments
  gendoc:
    name: Document generation
    runs-on: ubuntu-latest
    steps:
      - name: Install Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: v0.11.0
      - uses: actions/checkout@v4
      - name: Generate documentation
        run: make --silent documentation
        # Ensure that running the documentation generation does not produce any changes.
        # The documentation generated in the repository must be up to date
      - name: Check for changes
        run: if [[ -n $(git status -s) ]]; then exit 1; fi
